### ISSUE TITLE
Bug PDF ID to transition ID

### ISSUE THREAD

**Issue by jcsilva** [jimbozhang/gop-gmm#12]
I think there is a serious bug in your code. In line 52 of src/gop/gmm-gop.cc, there is:

```
pdfid_to_tid[tm_.TransitionIdToPdf(i)] = i;
```
But PDF ID's and transition'id can't be mapped this way. PDF's may be (and they usually are) shared between several HMM states. You may check it running the `show-transitions` tool.

On the other hand, transition id's are unique, as stated in  kaldi/src/hmm/transition-model.h. 

So, I think you should change the way you convert PDF ids to transtion. You should use a tuple as the key for your mapping.

**Comment by jimbozhang** [comment]
Thank you Eduardo, you are right. This is a big bug, I'll try to fix it
soon.

Eduardo Silva <notifications@github.com> 于 2018年6月13日周三 下午9:51写道：

**Comment by longfenghou** [comment]
@jcsilva hello, i have checked the pdfid and transition-id relationships in my tri1 model. It is as the following:
 PDF id is:0    Transition_id  i  is:0   
 PDF id is:0    Transition_id  i  is:1   
 PDF id is:0    Transition_id  i  is:2   
 PDF id is:0    Transition_id  i  is:3   
 PDF id is:0    Transition_id  i  is:4   
 PDF id is:200    Transition_id  i  is:5   
 PDF id is:200    Transition_id  i  is:6   
 PDF id is:200    Transition_id  i  is:7   
 PDF id is:200    Transition_id  i  is:8   
which means pdfid_to_tidp[] takes only the last transition_id as its value if the code is written currently.
So, apprently, this will not give the right transition id when we obtain a pdf_id from:

        KALDI_ASSERT(ctx_dep_.Compute(phoneseq, c, &pdf_id));
        int32 tid = pdfid_to_tid[pdf_id];
we need another indicator to establish a one-to-one relationship between pdf_id and transition_id, do you have any idea which indicator can be used here?

**Comment by jcsilva** [comment]
Well, this is precisely the bug I described above. Sorry, but I don't know which index you should use and I'm not sure if Kaldi has this index. I believe the implementation should be changed for calculating GOP without using indexes.

**Comment by alongwithyou** [comment]
let me try to fix it

**Comment by jimbozhang** [comment]
Thanks Xinglong @alongwithyou , I'm looking forward your PR ;)

**Comment by jimbozhang** [comment]
The transition-ids are only for building the denominator graph. Although one pdf-id may have multiple transition-ids, all those transitions-ids share the same HMM state (of course). So I think this implementation should be okay.
