### ISSUE TITLE
Confuse about code used for

### ISSUE THREAD

**Issue by tjrac** [jimbozhang/gop-gmm#20]
In the file "src/gop/dnn-gop.cc" I find the follow code in line 201 and line 202, but I do not know what is these codes used for, can you help me?
```
const Matrix<BaseFloat> features(feats_in_phone);
const Matrix<BaseFloat> online_ivectors_feat(ivector_in_phone);
```

**Comment by tbright17** [comment]
It basically does nothing. I believe you can just ignore it.
