### ISSUE TITLE
Neural network support

### ISSUE THREAD

**Issue by jimbozhang** [jimbozhang/gop-gmm#6]
Currently it is based on GMM. Need neural network support.

**Comment by leuski-ict** [comment]
I'm looking to do the same -- use nnet2 models instead of GMM. It is my understanding, that the changes would be to replace DecodableAmDiagGmmScaled with DecodableAmNnet and the appropriate model loading/configuration code. But the actual GOP calculation (making the FSTs and decoding with them) would be the same. Is this right or am I missing something?

**Comment by jimbozhang** [comment]
Yes, it is what I exactly want to do. Many thanks for your interest. Go ahead and I'm looking forward your pull request. 👍

**Comment by hyuezhi** [comment]
hi~ I found the dnn verison of your work, that is 'kaldi-dnn-ali-gop'. May i ask is there any trianed dnn model for testing this project?  

thanks

**Comment by jimbozhang** [comment]
@hyuezhi Thanks tbright17, the neural network support was added as a branch tbright17-dnn. You may find models at http://kaldi-asr.org/downloads/tree/trunk/

**Comment by hyuezhi** [comment]
I'll look into it, thank you very much~

**Comment by tbright17** [comment]
@hyuezhi Hi, if you want I can send you the nnet3 AM trained on Librispeech, which has been tested on the code. I don't know how to upload large AM files.

**Comment by hyuezhi** [comment]
yeah, that would be great! But i don't know how to upload the large files through the git-hub. But can you send me by my company's etrans? I am in _HUAWEI TECHNOLOGIES CO., LTD_., if you are convinient, can you give me your email edress, so I can establish a etrans channel. And I promise this is just for academic use. 

Thank you for your kind reply~   : )

**Comment by longfenghou** [comment]
@tbright17 hello, tbright17, is it possible for you to send me your nnet3 model files for the librispeech, i would like to have a test on the dnn version of the gop code.  Thanks very much!

**Comment by tbright17** [comment]
Sure. Please give me your email and I will send it to you via google drive.

**Comment by longfenghou** [comment]
@tbright17 Thanks, my email adresss are : 
longfenghou@gmail.com
longfenghou@126.com
Thanks a lot!

**Comment by heqiqi** [comment]
hi tbright17,
Can I have a trained model?
I want to have a test too.
heqiqi@gmail.com

Thanks a lot.

**Comment by lukeinator42** [comment]
@tbright17 
Hi tbright17,

I was wondering if I could get a copy of the model as well. My email is lukasgrasse@gmail.com

Thanks,
Lukas

**Comment by turnglight** [comment]
@tbright17
Hi tbright17,
Can I have a trained model?
I want to have a test too.

335771269@qq.com

Thank you very much.

**Comment by lmpanda** [comment]
Hi turnlight,

Sure, you can use these links:

https://s3.amazonaws.com/kaldi-dnn-ali-gop-models/dnn_model.tar.gz
https://s3.amazonaws.com/kaldi-dnn-ali-gop-models/gmm_model.tar.gz

I'm working on making this a part of the script, but for now you can just
download and extract to the relevant folder.

Best,
Lam

**Comment by lmpanda** [comment]
Just to clarify, the models I've sent you links to work well with tbright's
DNN-enabled version.
I believe that jimbozhang has his own trained model - you can ask him if
you need one.

**Comment by jimbozhang** [comment]
See https://github.com/kaldi-asr/kaldi/issues/3675 for the GOP-NN implementation.
